### ISSUE TITLE
Generated tables in latex do not compile

### ISSUE THREAD

**Issue by VincentBlondeau** [pillar-markup/pillar#119]
I tried to put in the pillar document:
```
|!Language |!Coolness
|Smalltalk | Hypra cool
|Java | baaad
```

The generated code is:
```
\begin{tabular}{ll}
\toprule
\textbf{Language} &amp; \textbf{Coolness} \\
\midrule
Smalltalk &amp; Hypra cool \\
Java &amp; baaad \\
\bottomrule
\end{tabular}
```

But:
* \toprule, \midrule and \bottomrule are not defined by the template I use, maybe you can add them if not defined
* &amp; is escaped and should be &
* How do I remove the rules and the vertical separators?

----
I am using stable Pharo4 v3.04

**Comment by cdlm** [comment]
`\toprule`, `\midrule`, `\bottomrule` are provided by `\usepackage{booktabs}`. A highly recommended package whenever you have tables in a LaTeX document, BTW. There shouldn't be any vertical separators (to get them the table format would need to be `|l|l|`)

**Comment by DamienCassou** [comment]
The conversion from `&` to `&amp;` is due to the mustache template you are using. By default, Mustache escapes all HTML characters (/cc @noha). Please give me your template and I will help you. The rule is:

- if you use default Mustache escaping, replace `{{content}}` by `{{{content}}}`
- if you use another escaping (e.g., you have in your document something like `{{=« »=}}`), prefix `content` by `&`, (e.g., `«& content»`).

/cc @YannDub @ThibaultAr You may want to reuse this when writing documentation.
