### ISSUE TITLE
Magritte based accessors should be defined

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/pillar#126]
I understand that configuration are described by magritte entities. 
Now I do not get why accessors are not part of the classes.

To me this is not good to have "broken" code such as 

activate
    super activate.
    self optionAt: 'to' ifPresent: [ :subconf | configuration defaultExporters: {subconf} ].
    self optionAt: 'path' ifPresent: [ :path | configuration outputFile: (RelativePath from: path) ].
    self parseInputFile.
    self export.
    self exitSuccess

where defaultExporters: is only there when the system.

**Comment by DamienCassou** [comment]
> Now I do not get why accessors are not part of the classes

what do you mean?

> where defaultExporters: is only there when the system. 

end of sentence missing

**Comment by Ducasse** [comment]
(thibault told me that the method was generated I thought it was using DNU) Both are a bad idea to me. 
 We should not have code invoked and with methods not defined (or defined dynamically).
It prevents browsing code and it will be a maintenance hell.

**Comment by jecisc** [comment]
In Cocoon before we got 3 methods by parameter of the configuration:
- the getter
- the setter
- the default value

In pillar, there is a lot of parameters, so in the end we had a class with *a lot* of methods and it was hard to use.

Now in Cocoon for a parameter you just have to define one method: the description. The configuration will use DNU in order to check the descriptions to invoke the right one.

I think that both ways have pros and cons. If it has to be change it should be pretty easy.

**Comment by DamienCassou** [comment]
DNU is indeed used. I agree with Steph that's not a really good solution. But implementing 2 methods for each configuration option with all the copy/pasting it involves is not really good either.

**Comment by guillep** [comment]
This will be reviewed soon. To me a good enough solution is to minimize pillar arguments.
The core of Pillar should have as few dependencies as possible in the configuration. Those should be "typed". Then, particular plugins should ask new ones, but those can be checked by the plugin itself.
