### ISSUE TITLE
Per-chapter metadata are ignored

### ISSUE THREAD

**Issue by cdlm** [pillar-markup/pillar#131]
The makefile-oriented build completely ignores per-chapter metadata; the intermediate JSON files only have data for `content… the`title`value from`pillar.conf` goes nowhere.

How do we get all that back ? Without this the whole template system looses a lot of its interest…

**Comment by Ducasse** [comment]
Luc fixed this in the dev branch we should check it and push it into stable

**Comment by Ducasse** [comment]
Hi damien 
this is fixed in the new released version of Pillar on 4.0.7 for pharo 50 and pharo 60. 
In the future we will drastically simplify the management of metadata (we will remove them and handle them and data). 
Metadata are making everything (lookup and all the rest) supercomplex for just a little optimisation and namespace like behavior. 
No need for that. 

KISS
