### ISSUE TITLE
Rename folder in archetypes/book/support/templates

### ISSUE THREAD

**Issue by cdlm** [pillar-markup/pillar#332]
this one: https://github.com/pillar-markup/pillar/tree/dev-7/archetypes/book/support/templates/latex:sbabook

It was always named latex and has no reason to be called like that (compare with the basic-latex archetype). Seems to break on windows too…

**Comment by Ducasse** [comment]
Fixed! We introduced folderName instead of using the writername. This way we decouple the logical name of the writer from its physical representation. 
Now  https://github.com/pillar-markup/pillar/tree/dev-7/archetypes/book/support/templates/latex:sbabook is  https://github.com/pillar-markup/pillar/tree/dev-7/archetypes/book/support/templates/latex


Stef and Asbath
