### ISSUE TITLE
Check the management of the link in LaTeX

### ISSUE THREAD

**Issue by jecisc** [pillar-markup/pillar#36]
In particular the links with an alias. In that case show an external link in footnote or in parenthesis. (\footnote{\ur{address}})

**Comment by YannDub** [comment]
It work partialy with #35 I think. ${footnote:\\url{address}}$ work for the moment.

**Comment by DamienCassou** [comment]
I guess what @jecisc means is that when the author writes:

```pillar
Please check the *project's webpage>http://project.io*.
```

The PDF must:
- contain a link `project's webpage` redirecting to the URL when clicked
- a footnote with the URL so that, when the PDF is printed, the reader can see the URL

If this is what @jecisc means, we can close that as Damien P. and I fixed it for Enterprise Pharo.

**Comment by jecisc** [comment]
This is exactly the meaning of this issue.I should have explained it better but when I opened this issue I was migrating all the issues so I did not took the time to explain it better.

This is fixed for EnterprisePharo but will it work for every LaTeX export? For example if I user Pillar to write a report and use this kind of syntax, will I lose my links?

**Comment by DamienCassou** [comment]
this is fixed for all documents written in Pillar :-)
