### ISSUE TITLE
Merge the concepts of Transformer and Phase

### ISSUE THREAD

**Issue by DamienCassou** [pillar-markup/pillar#56]
Transformer and phase are somewhat similar with a transformer being a special kind of phase where the input and output are documents. Phases need to be sorted. Maybe the order could be defined as `(category,position)` where

- `category` could be
  1. `initialization`
  1. `parse`
  1. `check`
  1. `transform`
  1. `export`
  1. `finishing`

- `position` could be either
  1. `before`,
  2. `during` or
  3. `after`

**Comment by DamienCassou** [comment]
A phase may have some configuration and thus could inherit from Cocoon configuration class. The `PRCocoonConfiguration` could have a `phases` parameter that returns an ordered list of of `PRPhase`. In the `pillar.conf`, when the user specifies `phases`, it must be interpreted as patch to apply to the default `phases` instead of a from-scratch specification of the list to avoid having to redefine everything for each little change to the list.

**Comment by DamienCassou** [comment]
Phase | `phaseSymbol` | `phasePriority` | description
---------|--------------------|------------------|----------------
`inputFile` | parse | after | I visit a document and transform an ==inputFile== annotation into the content of the file.
`numerator` | transform | before | I visit the file and add numbers to the titles, scripts, figures, and internals links.
`scriptEvaluator` | transform | after | I visit a document and I evaluate a script if his ==eval== parameter is ==true==.

**Comment by DamienCassou** [comment]
@cc what do you think?

**Comment by jecisc** [comment]
So for each `symbol` we would have 1 Phase at the `during` position, which is the current `actionOn:` ?

**Comment by DamienCassou** [comment]
that's my opinion yes. I'm not sure this is flexible enough. But flexibility comes at the price of complexity so we should find a balance

**Comment by jecisc** [comment]
In the paper that seems fine to me.

**Comment by DamienCassou** [comment]
Filling the table at https://github.com/pillar-markup/pillar/issues/56#issuecomment-137650719 is already not easy because phases depend on other phases, even in the same category. I guess there is a better way...

**Comment by YannDub** [comment]
Phases are a notion of priority, maybe we can bind category and priority instead of position. For example :

| Phases   | Category  | Priority | Description |
|:------------:|:-------------:|:----------:|:--------------:|
| parse      | parse        | 1          | transform an input file into a tree |
| inputFile | parse        | 2          | I visit a document and transform an ==inputFile== annotation into the content of the file |
| numerator | transform | 1 | I visit the file and add numbers to the titles, scripts, figures, and internals links |
| etc | etc | etc | etc |

**Comment by DamienCassou** [comment]
@YannDub yes, why not

**Comment by YannDub** [comment]
`Transformers` should not anymore be disable if they are all `phases` ?

**Comment by jecisc** [comment]
We **need** to be able to disable some transformers because some introduce security holes. For example the one executing scripts. If you do not trust the source of the pillar file you want to disable this transformer.

**Comment by YannDub** [comment]
I think `disableTransformer` need to be remove because the plan is to add a configuration tag `phases` and transformers does not exist anymore. A basic cycle phase could be

`parse -> fileInclusion -> numerator -> (some check) -> outputDirectoryCreation -> export`

And in a configuration file, we could be add some phases like :

`"phases" : [scriptEval, etc...]`

**Comment by YannDub** [comment]
Some transformer are started for a specific writers, for example sections in HTML. So we can't use this phases like other because they need to be active when it's the good writer and their keys are on the configuration

**Comment by YannDub** [comment]
All transformers are now phases, I no longer use pragmas, so PRTransformerDocumentation need to be updated.

**Comment by YannDub** [comment]
Now phases and transformers are all pipes.
