### ISSUE TITLE
pillar chapter does not show config parameters

### ISSUE THREAD

**Issue by DamienCassou** [pillar-markup/pillar#92]
This is in the chapter text instead:

```
MessageNotUnderstood: receiver of "new" is nil
```

**Comment by S0orax** [comment]
I tried to reproduce this bug, but I think this bug was fix this week end because when I regenerate the documentation in html, the expression who failed friday, don't fail today.

**Comment by jecisc** [comment]
I launched a build to check.

**Comment by jecisc** [comment]
On Jenkins the problem is still here

**Comment by ThibaultAr** [comment]
I've upgraded my Pillar's version this morning with the script 'download.sh', and when i generate the documentation Pillar.pillar, it works. 
I think the problem is fixed but not updated on the Jenkins.

**Comment by jecisc** [comment]
Jenkins should take the last green version of Pillar. 

Here is the script: 

    git log -n 10 > EnterprisePharo.gitlog
    tar zcf .EnterprisePharo-src.tgz *
    mv .EnterprisePharo-src.tgz EnterprisePharo-src.tgz   # lastSuccessful used by Pillar for testing 
    
    ./download.sh
    ./compile.sh
    ./compileBook.sh

**Comment by ThibaultAr** [comment]
So, I have reproduce the bug. When i take the script download.sh from the jenkins it doesn't works, the latex file generated produce an error. But when i take the script download.sh that i took at : http://smalltalkhub.com/#!/~Pier/Pillar , it works. I think it's a problem of version of Pillar because the main difference between the two scripts is :
<pre><code> 
$ diff download.sh ../Pillar/download.sh 
4,6c4
 IMAGE_URL="https://ci.inria.fr/pharo-contribution/job/Pillar/PHARO=40,VERSION=<strong>development</strong>,VM=vm/lastSuccessfulBuild/artifact/Pillar.zip"
 PHARO_VM=${PHARO_VM:-./pharo}
 
 IMAGE_URL="https://ci.inria.fr/pharo-contribution/job/Pillar/PHARO=40,VERSION=<strong>stable</strong>,VM=vm/lastSuccessfulBuild/artifact/Pillar-deployment.zip"
</code></pre>

Maybe we should updgrade the script on the jenkins.

**Comment by ThibaultAr** [comment]
I have find the source of the bug : In the development version of Pillar, PRCocoonConfiguration is now PRPillarConfiguration (#86).
<pre><code> $ ./compile.sh 
Chemin de sous-module 'support/latex/sbabook' : 'a4239e3710a964a461ce0971c7a2f7456cd00fd3' extrait

PRScriptEvaluationEnvironment>>DoIt (<strong>PRCocoonConfiguration is Undeclared</strong>) 

*** Warning: PRReferenceNotFound: Can't find anchor named 'sec:confParam:template'                                                                                                                                                 
</code></pre>


So, here is the updated PillarChap with the bug fixed.
[Updated_PillarChap.zip](https://github.com/pillar-markup/pillar/files/98987/Updated_PillarChap.zip)

**Comment by DamienCassou** [comment]
I guess I can close the issue now. Thank you
